[package]
name = "distributed-kv-store"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
libp2p = { version = "0.46",  features = ["tcp-tokio"] }
tokio = { version = "1.19", features = ["full"] }
futures = "0.3.1"
tracing = "0.1"
tracing-subscriber = "0.3"